name: Publish Python Package

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version to publish (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          
      - name: Build package
        run: |
          cd replayer-adapter-python
          python -m build
          
      - name: Run tests (if available)
        run: |
          cd replayer-adapter-python
          pip install -e ".[dev]"
          python -m pytest tests/ -v
        continue-on-error: true
          
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cd replayer-adapter-python
          python -m twine upload --repository pypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          
      - name: Manual publish to PyPI
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd replayer-adapter-python
          # Update version in pyproject.toml if provided
          if [ -n "${{ github.event.inputs.version }}" ]; then
            sed -i 's/version = ".*"/version = "${{ github.event.inputs.version }}"/' pyproject.toml
          fi
          python -m build
          python -m twine upload --repository pypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changes in this release
            
            This release includes updates to the Temporal Workflow Debugger Python replayer adapter.
            
            ### Package: temporal-replayer-adapter-python
            
            - Version: ${{ github.ref_name }}
            - Built from commit: ${{ github.sha }}
          draft: false
          prerelease: false 