name: Publish Go Package

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version to publish (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/go/pkg/cache
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - name: Test Go package
        run: |
          cd replayer-adapter-go
          go mod download
          go test ./... -v
        continue-on-error: true
          
      - name: Build Go package
        run: |
          cd replayer-adapter-go
          go build -v ./...
          
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changes in this release
            
            This release includes updates to the Temporal Workflow Debugger Go replayer adapter.
            
            ### Package: temporal-replayer-adapter-go
            
            - Version: ${{ github.ref_name }}
            - Built from commit: ${{ github.sha }}
            - Go version: 1.23
            
            ### Installation
            
            ```bash
            go get github.com/phuongdnguyen/temporal-workflow-debugger/replayer-adapter-go@${{ github.ref_name }}
            ```
          draft: false
          prerelease: false
          
      - name: Manual release creation
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Manual release triggered for version: ${{ github.event.inputs.version }}"
          echo "To create a release, push a tag with the version:"
          echo "git tag v${{ github.event.inputs.version }}"
          echo "git push origin v${{ github.event.inputs.version }}" 